### ISSUE TITLE
notMNIST_input.py 執行問題

### ISSUE THREAD

**Issue by k0286** [kevin28520/My-TensorFlow-tutorials#1]
我在youtube看了你的tutorial，然後抓了這份code來玩看看。

發現line `215~235`可能有問題，一直出錯。

再參考了網路上其他的範例和stackoverflow後

在line `216`增加
```python
init = tf.initialize_all_variables()
sess.run(init)
```
之後才能夠正常執行。

**Comment by kevin28520** [comment]
Thank you very much!
It works well on my side, but I will check it.
